import { Inter } from "next/font/google";
import Head from "next/head"; // Import Head from 'next/head'
import "./globals.css";
import Navbar from "@/Components/Navbar";
import AuthContext from "@/Context/authContext";
import { Provider } from 'react-redux';
import { store } from "@/ReduxToolkit/Store/store";
import Providers from "@/ReduxToolkit/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
    <html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* Apply Inter font */}
        <style>{inter}</style>
      </Head>
      <body>
        <Providers>
          <AuthContext>
            <Navbar />
            {children}
          </AuthContext>
        </Providers>
      </body>
      </html>
    </>
  );
}
